spring.config.import=file:env.properties
spring.application.name=aziendale

# SERVER CONFIG
server.port=${PORT}
# DB CONFIG
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver=org.postgresql.Driver
# HIBERNATE
spring.jpa.hibernate.ddl-auto=update
# JWT
jwt.secret=${JWT_SECRET}
# RESEND
resend.api.key=${RESEND_API_KEY}
resend.from.email=Gestionale Aziendale <onboarding@resend.dev>